# Generated by Django 2.0.3 on 2019-05-21 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('dynasty', models.CharField(max_length=64)),
                ('type', models.CharField(max_length=16)),
                ('color', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('nickName', models.CharField(max_length=64)),
                ('pwd', models.CharField(max_length=64)),
                ('level', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserAuthorsInfoPreset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dmdb.AuthorsInfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dmdb.User')),
            ],
        ),
        migrations.CreateModel(
            name='Var',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ZhToHant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zh', models.CharField(max_length=255)),
                ('hant', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='presets',
            field=models.ManyToManyField(through='dmdb.UserAuthorsInfoPreset', to='dmdb.AuthorsInfo'),
        ),
    ]
