# Generated by Django 2.0.3 on 2019-05-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmdb', '0002_authorsinfo_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorsinfo',
            name='area',
            field=models.CharField(default='未知', max_length=64),
        ),
    ]
