# Generated by Django 2.0.3 on 2019-06-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmdb', '0003_authorsinfo_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='var',
            name='value',
            field=models.CharField(max_length=4096),
        ),
    ]
